@startuml

usecase "/engage_button_manager"
usecase "/engage_srv_converter" #LightCoral
usecase "/autoware_state_machine"
rectangle "autoware" {
  usecase "/control/vehicle_cmd_gate"
}

(/engage_button_manager) --> (/engage_srv_converter) : /engage_button_manager/output/engage_button
(/engage_srv_converter) --> (/autoware_state_machine) : /api/external/set/engage
(/engage_srv_converter) <.. (/autoware_state_machine)
(/autoware_state_machine) --> (/control/vehicle_cmd_gate) : /api/autoware/set/engage
(/autoware_state_machine) <.. (/control/vehicle_cmd_gate)
@enduml
